# Generated by Django 3.2.4 on 2021-06-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menuoption_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('youtube_link', models.CharField(max_length=150)),
                ('excercises', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
