# Generated by Django 3.2.4 on 2021-06-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210619_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='youtube_link',
            new_name='youtube_code',
        ),
    ]
