# Generated by Django 3.2.4 on 2021-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_youtube_link_exercise_youtube_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
