# Generated by Django 3.2.4 on 2021-06-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exercise_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='exercise',
            name='menu_option',
            field=models.CharField(default='', max_length=50),
        ),
    ]
