# Generated by Django 3.2.4 on 2021-06-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210620_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='menu_option',
            new_name='title',
        ),
    ]
