# Generated by Django 3.2.4 on 2021-06-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_menu_option_exercise_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='title',
        ),
        migrations.AddField(
            model_name='exercise',
            name='menu_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.menuoption'),
            preserve_default=False,
        ),
    ]
